language: c

addons:
  apt:
    packages:
    - ia32-libs
    - ia32-libs-multiarch
    - libgd2-xpm

install:
    - source armenv.sh

script:
    - source armenv.sh; make

notifications:
    email: false


